# Generated by Django 4.0.3 on 2022-04-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Name', models.CharField(max_length=55)),
                ('S_Address', models.CharField(max_length=60)),
                ('S_Parent', models.CharField(max_length=55)),
                ('S_Course', models.TextField()),
                ('S_id', models.IntegerField()),
                ('S_description', models.CharField(max_length=12)),
            ],
        ),
    ]
