# Generated by Django 4.0.3 on 2022-04-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_course_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentAddress',
            field=models.CharField(max_length=54),
        ),
    ]
