# Generated by Django 4.0.3 on 2022-04-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_crops'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='image',
            field=models.ImageField(default=2, upload_to='image/'),
            preserve_default=False,
        ),
    ]
